### PR TITLE
Refactor decode

### PR DESCRIPTION
**Pull request by kcsongor**
This is my attempt at removing some duplication from instruction decoding.

Not finished yet, just opened the PR for discussion!

In particular, I don't think the bit manipulation instructions fetch the next word from memory, so I changed the behaviour of those, the rest _should_ be functionally the same as before

### CODE REVIEW

**Comment by davedissian** [comment]
How come you concluded that the bit instructions fetch the next word from memory? From what I can tell based on (this)[http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf] manual on page 108, selecting a bit from register A always has opcode CB 47, which implies that the parameter is the next byte much like load immediate/etc.

**Comment by kcsongor** [comment]
The current implementation (https://github.com/davedissian/gbc-emulator/blob/master/src/cpu/ops.rs#L466) seems to load the next word (byte).
I mean immediate values also come from memory if I'm not mistaken? (Since they take up a full word)

If this was the case, then the 0xCB-prefixed instructions would not cover the whole range 0x00-0xFF available to them, which would be wasteful. Besides, the select bit ranges 0-7, which can be encoded in 3 bits, so having an immediate 8 bit to them was also a bit suspicious.

According to this table: http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html
the BIT selection (following a 0xCB) has the pattern `0 1 [b] [reg]`, where both `[b]` and `[reg]` are 3 bits long.

Either way, I'm planning on setting up some unit tests to check if the instructions are correctly decoded according to _some_ specification (but it seems they don't always agree 😄 )

**Comment by davedissian** [comment]
I agree with you there. Perhaps a good idea would be to check out other implementations of GB/GBC emulators to see what they do with it. Either way, it would be useful to add a comment near them saying that this is (currently) ambiguous. Once the CPU can actually execute code, these will be useful: http://gbdev.gg8.se/files/roms/blargg-gb-tests/

**Comment by kcsongor** [comment]
I've moved out the instruction fetching from decode, so now it should be a pure function.
In order to prevent leaking the decode logic to other parts of the code when decode can't immediately construct the full instruction (CB prefix, immediate value), decode returns either the full instruction or a continuation (via a closure), that when given the remaining information (u8 or u16), constructs the final structure.

**Comment by kcsongor** [comment]
Added (exhaustive) test cases for the non-CB instructions and fixed the bugs. This means that the decoder (excluding the CB instructions, for which I will add test cases later) is correct!

**Pull request merged**
